# fly.toml app configuration file generated for oracle-bot on 2024-01-16

app = "oracle-bot-v1" # Можно будет изменить при первом запуске
primary_region = "ams" # Амстердам (близко к РФ), можно выбрать другой

[build]
  dockerfile = "Dockerfile"

# Монтируем диск для базы данных SQLite, чтобы данные не исчезали
[mounts]
  source = "oracle_data"
  destination = "/app/data"

[env]
  # Указываем путь к БД на смонтированном диске
  DATABASE_URL = "sqlite:///data/database.db"

# Настройки процесса
[processes]
  app = "python main.py"
