# fly.toml app configuration file
app = 'orc'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

# Монтируем диск для базы данных
[mounts]
  source = "oracle_data"
  destination = "/app/data"

[env]
  # Используем базу на диске
  DATABASE_URL = "sqlite:///data/database.db"

# Настройки виртуальной машины
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
